-- 文化・学問・地域・芸術を追加し、全大ジャンルに子ジャンルを厚く載せる
insert into public.major_categories (id, name, icon, sort_order, is_active) values
  ('youtube',     'YouTube',        'Video',            1,  true),
  ('books',       '本',              'BookOpen',         2,  true),
  ('manga',       '漫画',            'BookMarked',       3,  true),
  ('movies',      '映画',            'Film',             4,  true),
  ('anime',       'アニメ',          'Sparkles',         5,  true),
  ('drama',       'ドラマ',          'Tv',               6,  true),
  ('music',       '音楽',            'Music',            7,  true),
  ('games',       'ゲーム',          'Gamepad2',         8,  true),
  ('radio',       'ラジオ',          'Radio',            9,  true),
  ('apps',        'アプリ',          'Cpu',              10, true),
  ('food',        'メシ',            'UtensilsCrossed',  11, true),
  ('gadgets',     'ガジェット',      'Lightbulb',        12, true),
  ('spots',       '場所',            'MapPin',           13, true),
  ('photo',       '写真',            'Camera',           14, true),
  ('fashion',     '服',              'Shirt',            15, true),
  ('streaming',   '配信',            'Cast',             16, true),
  ('theater',     '舞台',            'Drama',            17, true),
  ('doujin',      '同人',            'PenTool',          18, true),
  ('occult',      'オカルト',        'Ghost',            19, true),
  ('creatures',   '生き物',          'PawPrint',         20, true),
  ('culture',     '文化',            'Landmark',         21, true),
  ('academia',    '学問',            'GraduationCap',    22, true),
  ('region',      '地域',            'MapPinned',        23, true),
  ('art',         '芸術',            'Palette',          24, true),
  ('other',       'その他',          'MoreHorizontal',   25, true)
on conflict (id) do update set
  name = excluded.name,
  icon = excluded.icon,
  sort_order = excluded.sort_order,
  is_active = true;

insert into public.sub_categories (id, major_category_id, name, sort_order, is_active) values
  ('yt-education',       'youtube', '解説・教育',       1, true),
  ('yt-vlog',            'youtube', 'Vlog',             2, true),
  ('yt-gaming',          'youtube', 'ゲーム実況',       3, true),
  ('yt-cooking',         'youtube', '料理',             4, true),
  ('yt-entertainment',   'youtube', 'エンタメ',         5, true),
  ('yt-music',           'youtube', '音楽',             6, true),
  ('yt-science',         'youtube', '科学',             7, true),
  ('yt-review',          'youtube', 'レビュー',         8, true),
  ('yt-doc',             'youtube', 'ドキュメンタリー', 9, true),
  ('yt-asmr',            'youtube', 'ASMR',            10, true),
  ('yt-clip',            'youtube', '切り抜き',        11, true),
  ('yt-live',            'youtube', 'ライブ',          12, true),
  ('books-novel',        'books',   '小説',             1, true),
  ('books-nonfiction',   'books',   'ノンフィクション', 2, true),
  ('books-business',     'books',   'ビジネス書',       3, true),
  ('books-manga',        'books',   '漫画',             4, true),
  ('books-light-novel',  'books',   'ライトノベル',     5, true),
  ('books-essay',        'books',   'エッセイ',         6, true),
  ('books-poetry',       'books',   '詩',               7, true),
  ('books-academic',     'books',   '学術書',           8, true),
  ('books-children',     'books',   '児童書',           9, true),
  ('books-practical',    'books',   '実用書',          10, true),
  ('books-classic',      'books',   '古典',            11, true),
  ('books-criticism',    'books',   '評論',            12, true),
  ('manga-shonen',       'manga',   '少年',             1, true),
  ('manga-shojo',        'manga',   '少女',             2, true),
  ('manga-seinen',       'manga',   '青年',             3, true),
  ('manga-josei',        'manga',   '女性',             4, true),
  ('manga-web',          'manga',   'Web漫画',          5, true),
  ('manga-gag',          'manga',   'ギャグ',           6, true),
  ('manga-horror',       'manga',   'ホラー',           7, true),
  ('manga-gourmet',      'manga',   'グルメ',           8, true),
  ('manga-sports',       'manga',   'スポーツ',         9, true),
  ('manga-history',      'manga',   '歴史',            10, true),
  ('movies-action',      'movies',  'アクション',       1, true),
  ('movies-sf',          'movies',  'SF',               2, true),
  ('movies-drama',       'movies',  'ドラマ',           3, true),
  ('movies-anime',       'movies',  'アニメ映画',       4, true),
  ('movies-documentary', 'movies',  'ドキュメンタリー', 5, true),
  ('movies-comedy',      'movies',  'コメディ',         6, true),
  ('movies-horror',      'movies',  'ホラー',           7, true),
  ('movies-romance',     'movies',  '恋愛',             8, true),
  ('movies-suspense',    'movies',  'サスペンス',       9, true),
  ('movies-japan',       'movies',  '日本映画',        10, true),
  ('movies-world',       'movies',  '外国映画',        11, true),
  ('movies-indie',       'movies',  'インディー',      12, true),
  ('anime-tv',           'anime',   'TV',               1, true),
  ('anime-movie',        'anime',   '劇場',             2, true),
  ('anime-ova',          'anime',   'OVA',              3, true),
  ('anime-late',         'anime',   '深夜',             4, true),
  ('anime-kids',         'anime',   '子供向け',         5, true),
  ('anime-mecha',        'anime',   'ロボット',         6, true),
  ('anime-slice',        'anime',   '日常',             7, true),
  ('anime-isekai',       'anime',   '異世界',           8, true),
  ('anime-music',        'anime',   '音楽',             9, true),
  ('anime-sports',       'anime',   'スポーツ',        10, true),
  ('drama-jp',           'drama',   '国内',             1, true),
  ('drama-world',        'drama',   '海外',             2, true),
  ('drama-stream',       'drama',   '配信オリジナル',   3, true),
  ('drama-asadora',      'drama',   '朝ドラ',           4, true),
  ('drama-police',       'drama',   '刑事',             5, true),
  ('drama-medical',      'drama',   '医療',             6, true),
  ('drama-jidai',        'drama',   '時代劇',           7, true),
  ('drama-romance',      'drama',   '恋愛',             8, true),
  ('drama-family',       'drama',   '家族',             9, true),
  ('music-jpop',         'music',   'J-POP',            1, true),
  ('music-rock',         'music',   'ロック',           2, true),
  ('music-classical',    'music',   'クラシック',       3, true),
  ('music-jazz',         'music',   'ジャズ',           4, true),
  ('music-anime',        'music',   'アニソン',         5, true),
  ('music-hiphop',       'music',   'ヒップホップ',     6, true),
  ('music-electro',      'music',   'エレクトロ',       7, true),
  ('music-folk',         'music',   'フォーク',         8, true),
  ('music-metal',        'music',   'メタル',           9, true),
  ('music-idol',         'music',   'アイドル',        10, true),
  ('music-soundtrack',   'music',   'サントラ',        11, true),
  ('music-world',        'music',   'ワールド',        12, true),
  ('games-rpg',          'games',   'RPG',              1, true),
  ('games-action',       'games',   'アクション',       2, true),
  ('games-indie',        'games',   'インディー',       3, true),
  ('games-board',        'games',   'ボードゲーム',     4, true),
  ('games-fps',          'games',   'FPS',              5, true),
  ('games-sim',          'games',   'シミュレーション', 6, true),
  ('games-puzzle',       'games',   'パズル',           7, true),
  ('games-rhythm',       'games',   '音ゲー',           8, true),
  ('games-social',       'games',   'ソシャゲ',         9, true),
  ('games-retro',        'games',   'レトロ',          10, true),
  ('games-fight',        'games',   '対戦',            11, true),
  ('radio-late',         'radio',   '深夜',             1, true),
  ('radio-local',        'radio',   'ローカル',         2, true),
  ('radio-net',          'radio',   'ネットラジオ',     3, true),
  ('radio-talk',         'radio',   'トーク',           4, true),
  ('radio-music',        'radio',   '音楽番組',         5, true),
  ('radio-news',         'radio',   'ニュース',         6, true),
  ('radio-reading',      'radio',   '朗読',             7, true),
  ('apps-prod',          'apps',    '生産性',           1, true),
  ('apps-sns',           'apps',    'SNS',              2, true),
  ('apps-create',        'apps',    '創作',             3, true),
  ('apps-learn',         'apps',    '学習',             4, true),
  ('apps-health',        'apps',    '健康',             5, true),
  ('apps-utility',       'apps',    '便利ツール',       6, true),
  ('apps-extension',     'apps',    '拡張機能',         7, true),
  ('apps-oss',           'apps',    'オープンソース',   8, true),
  ('food-washoku',       'food',    '和食',             1, true),
  ('food-chinese',       'food',    '中華',             2, true),
  ('food-western',       'food',    '洋食',             3, true),
  ('food-noodles',       'food',    '麺',               4, true),
  ('food-bread',         'food',    'パン',             5, true),
  ('food-sweets',        'food',    'スイーツ',         6, true),
  ('food-drink',         'food',    '酒',               7, true),
  ('food-cafe',          'food',    'カフェ',           8, true),
  ('food-home',          'food',    '自炊',             9, true),
  ('food-bgrade',        'food',    'B級',             10, true),
  ('gadgets-phone',      'gadgets', 'スマホ',           1, true),
  ('gadgets-pc',         'gadgets', 'PC',               2, true),
  ('gadgets-audio',      'gadgets', '音響',             3, true),
  ('gadgets-camera',     'gadgets', 'カメラ周辺',       4, true),
  ('gadgets-kitchen',    'gadgets', 'キッチン家電',     5, true),
  ('gadgets-light',      'gadgets', '照明',             6, true),
  ('gadgets-wearable',   'gadgets', 'ウェアラブル',     7, true),
  ('gadgets-stationery', 'gadgets', '文房具ガジェット', 8, true),
  ('spots-shop',         'spots',   '店',               1, true),
  ('spots-park',         'spots',   '公園',             2, true),
  ('spots-architecture', 'spots',   '建築',             3, true),
  ('spots-station',      'spots',   '駅',               4, true),
  ('spots-shrine',       'spots',   '寺社',             5, true),
  ('spots-museum',       'spots',   '博物館',           6, true),
  ('spots-night',        'spots',   '夜景',             7, true),
  ('spots-hidden',       'spots',   '穴場',             8, true),
  ('spots-onsen',        'spots',   '温泉',             9, true),
  ('spots-library',      'spots',   '図書館',          10, true),
  ('photo-snap',         'photo',   'スナップ',         1, true),
  ('photo-landscape',    'photo',   '風景',             2, true),
  ('photo-portrait',     'photo',   'ポートレート',     3, true),
  ('photo-record',       'photo',   '記録',             4, true),
  ('photo-film',         'photo',   'フィルム',         5, true),
  ('photo-street',       'photo',   '街撮り',           6, true),
  ('photo-nature',       'photo',   '自然',             7, true),
  ('photo-architecture', 'photo',   '建築写真',         8, true),
  ('fashion-wear',       'fashion', '服',               1, true),
  ('fashion-shoes',      'fashion', '靴',               2, true),
  ('fashion-vintage',    'fashion', '古着',             3, true),
  ('fashion-uniform',    'fashion', 'ユニフォーム',     4, true),
  ('fashion-accessory',  'fashion', 'アクセサリー',     5, true),
  ('fashion-bag',        'fashion', 'バッグ',           6, true),
  ('fashion-style',      'fashion', '着こなし',         7, true),
  ('fashion-workwear',   'fashion', '作業着',           8, true),
  ('stream-chat',        'streaming','雑談',            1, true),
  ('stream-game',        'streaming','ゲーム配信',      2, true),
  ('stream-song',        'streaming','歌',              3, true),
  ('stream-vtuber',      'streaming','VTuber',          4, true),
  ('stream-work',        'streaming','作業配信',        5, true),
  ('stream-study',       'streaming','勉強配信',        6, true),
  ('stream-clip',        'streaming','切り抜き',        7, true),
  ('th-play',            'theater', '演劇',             1, true),
  ('th-musical',         'theater', 'ミュージカル',     2, true),
  ('th-rakugo',          'theater', '落語',             3, true),
  ('th-manzai',          'theater', '漫才',             4, true),
  ('th-live',            'theater', 'ライブ',           5, true),
  ('th-classic',         'theater', '古典芸能',         6, true),
  ('th-small',           'theater', '小劇場',           7, true),
  ('doujin-manga',       'doujin',  '漫画',             1, true),
  ('doujin-novel',       'doujin',  '小説',             2, true),
  ('doujin-music',       'doujin',  '音楽',             3, true),
  ('doujin-game',        'doujin',  'ゲーム',           4, true),
  ('doujin-illust',      'doujin',  'イラスト',         5, true),
  ('doujin-event',       'doujin',  '即売会',           6, true),
  ('doujin-fan',         'doujin',  '二次創作',         7, true),
  ('doujin-original',    'doujin',  'オリジナル',       8, true),
  ('occult-ghost',       'occult',  '心霊',             1, true),
  ('occult-urban',       'occult',  '都市伝説',         2, true),
  ('occult-folk',        'occult',  '民俗',             3, true),
  ('occult-ufo',         'occult',  'UFO',              4, true),
  ('occult-fortune',     'occult',  '占い',             5, true),
  ('occult-kaidan',      'occult',  '怪談',             6, true),
  ('occult-book',        'occult',  'オカルト本',       7, true),
  ('occult-ritual',      'occult',  '儀式',             8, true),
  ('creature-dog',       'creatures','犬',              1, true),
  ('creature-cat',       'creatures','猫',              2, true),
  ('creature-bird',      'creatures','鳥',              3, true),
  ('creature-bug',       'creatures','虫',              4, true),
  ('creature-fish',      'creatures','魚',              5, true),
  ('creature-wild',      'creatures','野生',            6, true),
  ('creature-plant',     'creatures','植物観察',        7, true),
  ('creature-myth',      'creatures','架空の生き物',    8, true),
  ('culture-festival',   'culture', '祭り',             1, true),
  ('culture-manner',     'culture', '作法',             2, true),
  ('culture-language',   'culture', '言語文化',         3, true),
  ('culture-sub',        'culture', 'サブカル',         4, true),
  ('culture-pop',        'culture', '大衆文化',         5, true),
  ('culture-tradition',  'culture', '伝統芸能',         6, true),
  ('culture-food',       'culture', '食文化',           7, true),
  ('culture-dress',      'culture', '衣服文化',         8, true),
  ('culture-folktale',   'culture', '民話',             9, true),
  ('culture-net',        'culture', 'ネット文化',      10, true),
  ('culture-world',      'culture', '海外文化',        11, true),
  ('culture-youth',      'culture', '若者文化',        12, true),
  ('acad-philosophy',    'academia','哲学',             1, true),
  ('acad-history',       'academia','歴史学',           2, true),
  ('acad-literature',    'academia','文学',             3, true),
  ('acad-linguistics',   'academia','言語学',           4, true),
  ('acad-sociology',     'academia','社会学',           5, true),
  ('acad-psychology',    'academia','心理学',           6, true),
  ('acad-physics',       'academia','物理学',           7, true),
  ('acad-biology',       'academia','生物学',           8, true),
  ('acad-engineering',   'academia','工学',             9, true),
  ('acad-medicine',      'academia','医学',            10, true),
  ('acad-law',           'academia','法学',            11, true),
  ('acad-economics',     'academia','経済学',          12, true),
  ('acad-math',          'academia','数学',            13, true),
  ('acad-education',     'academia','教育学',          14, true),
  ('region-local',       'region',  '地元',             1, true),
  ('region-rural',       'region',  '田舎',             2, true),
  ('region-city',        'region',  '大都市',           3, true),
  ('region-shotengai',   'region',  '商店街',           4, true),
  ('region-port',        'region',  '港町',             5, true),
  ('region-campus',      'region',  '学園都市',         6, true),
  ('region-tourist',     'region',  '観光地',           7, true),
  ('region-depop',       'region',  '過疎地',           8, true),
  ('region-abroad',      'region',  '海外の街',         9, true),
  ('region-dialect',     'region',  '方言',            10, true),
  ('region-gotouchi',    'region',  'ご当地',          11, true),
  ('region-housing',     'region',  '団地・住宅地',    12, true),
  ('art-painting',       'art',     '絵画',             1, true),
  ('art-sculpture',      'art',     '彫刻',             2, true),
  ('art-design',         'art',     'デザイン',         3, true),
  ('art-architecture',   'art',     '建築',             4, true),
  ('art-craft',          'art',     '工芸',             5, true),
  ('art-contemporary',   'art',     '現代美術',         6, true),
  ('art-illust',         'art',     'イラスト',         7, true),
  ('art-calligraphy',    'art',     '書',               8, true),
  ('art-install',        'art',     'インスタレーション', 9, true),
  ('art-photo',          'art',     '写真表現',        10, true),
  ('art-moving',         'art',     '映像芸術',        11, true),
  ('other-diary',        'other',   '日記',             1, true),
  ('other-mix',          'other',   '複合',             2, true),
  ('other-experiment',   'other',   '実験',             3, true),
  ('other-unclassified', 'other',   '未分類',           4, true)
on conflict (id) do nothing;
